resources:
- name: git-repo
  public: true
  type: git
  icon: github-circle 
  source: 
    uri: "https://github.com/nayamama/groovy_java.git"
    branch: master
    private_key: |
      PuTTY-User-Key-File-2: ssh-rsa
      Encryption: none
      Comment: rsa-key-20160329
      Public-Lines: 6
      AAAAB3NzaC1yc2EAAAABJQAAAQEAubRGbtaNVkC7QiE+HU039RB6hY4pjPFt9Zue
      jYBayTBcNr/FYqjdf098ttcwDUFdNyHkVqpDyH2BdD/uLiExQtbuMjRE/4tcv5+E
      lPubNK2S9TZq/CRaMStZmvBdLwVma//XHDyAyD5KiCv+P6io1pcb3tYctw7SJKDZ
      POOvm/CGw1KXrqbLxHTu/yhruPiqU3ZuxT/y9TfazVXR5Ls8WCwVA+5Zy2RnVdlA
      IeXNI9naR4U6zpwLdzqToscSsr0A5qWn8YnHhK69OCUn43KFQJ+/WTQNVp3E+x1c
      cpwV8VZHvGFgIofqPJyk1QdGJ4kcSfQ9HdED44x20f7njIzK2Q==
      Private-Lines: 14
      AAABABkYXIuExv3RZWnNJBHMKigJJVBRezyPVAxu+cAYQ56lq5iyIZe19GsmasyZ
      nrWu4xVJxOkd7Xv1SNhbqpCcs6E/o6XrY0Ugq6sxO24UKbsCsv6K0C/pPJ7cWDeI
      Q/GY8ipFKugj2g042aOy6wGvAg8pLUegZL7Kpsat89fLvcj2wkdcsKuvAMU/VjAF
      VOCYhOHdaZBk+/Fg/KeSUl/3uFnOHASqfRB3aHIb43+qXmuNCEJhAkeNFo3IvSFd
      Cj+GvDIjTj/4TXSEkRpnP/JghaqrHeeaHiz2hK9SoH5sonDtZ04W0fJELrSqKEMG
      VLgRRzAqQMghv2f2FwOvdjVNTWEAAACBAO7r8t2K+0g1xMUuZ2z0PY4UWS/8d+vj
      ghHW6yUgCoPZPAOsTUQ07C3nZjmLbCSxSqgGQDP4hbPZLqdR6OS6Fm5jBWzUNh6t
      I36lYh0DHcXGJn3tkxQRTu45RZdIbsu0521/PicGIVhWTPkdlGIY7RPpr99dJL6m
      hsm5Cdck3h/XAAAAgQDG+n6exs+xDkHfOjMkRrjehIOYAqmLfegU6y/ky1RkTMeo
      aE0RtjfOIgsMsoztvRUoVhDCxJvj6z50wGDiIo5VEJr4EL/SEulzNcb+eFdIvrow
      7PlNK8g0Ftq7HDyYK/h3Ya2N6G4FE8roLd2kVhwsyKVLKuW81U8Cynw/Q6XUzwAA
      AIEAmyolVjEUbUip/7LDO6UY27JBhxqvUr9J/56bYaicPrVeNz9tSHXrfMslUB0O
      6I2T/dyxMUyjZEEPy4Qwyx3IIkR880/VR1L0I2vRywD0qaWcosFpwEeWDGVcbWBZ
      6iQHHcVvtJvnZ1hWCzZcniNyx+q4bQeFL5v1s4hrFDa+9zY=
      Private-MAC: 605293f9e4c7f046af98f6d30e3d9a13aaf22123

- name: test-repo
  type: git
  icon: github-circle 
  source: 
    uri: "https://github.com/nayamama/concourse_pp_test.git"
    branch: master

- name: my-timer
  type: time
  source:
    interval: 2m

jobs:
  - name: map-resource-in-another-folder
    public: true
    plan:
      - get: git-repo
      - get: test-repo
      - get: my-timer
        trigger: true
      - task: check-folder-structure
        file: test-repo/commit_output/update_repo.yml
      - put: git-repo
        params:
          repository: update-git
