resources:
- name: git-repo
  public: true
  type: git
  icon: github-circle 
  source: 
    #uri: "https://github.com/nayamama/groovy_java.git"  # not working
    uri: "git@github.com/nayamama/groovy_java.git"
    branch: master
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEArSKizEyNfGv/+7KZwfmGNauMBJPGATqF5k2B8b/gPGc6BqTL
      li99VeSoMcJUaIFJTg6jdjn7b7237IDAZ+3ItkuvhoBKNWvy3YIQd+OdLRB3MrP7
      5nPvD2o9Ji8jxZZUHAq3ULVt6UUrhWgLYoLqQA7doq5ZtF/eOpALQulgZaB+ZDsY
      6nJIagbcjbmJhJF4/GuAW4cyIhjOYlwnxesQ1BjmtDgTcdo/1AlOOjN8no2ZHTWp
      KMxgx1p4C5fdCrvLymy+gfk4GJNFIvP3Rn91BivTf8MeZ4nJDm9hAadR2mO1Kht+
      +iVQiyIEpn+PIQJykA1p3sRc8oO2RcuSctKFgwIDAQABAoIBABgd8AF3VGoVfTXp
      XgOoJ2rId5uXnghDx60Z9NTg/nJLisisIfPMr6/MRyWPRUS9ZaGq5lgsoXqiOcGG
      +cZAWCoUhuG8cxnX7J+wY2zf1uAVIBV+/sLOOWmzSctM27XFR/gUAg8LBsFssjBG
      Gvfg9pJvv63OjY5ToFgWAouSiKv/IXRdDhk5uFt5nLvPeO42gnJes3OOieFLYURq
      h00xridxDB93YyOefQTY4y+YAoiQBROTqM5Vu022t2vcA6pL46cFbz7+fl/Mh63I
      0qIh0mrQ6wFv/wADZBtPsZQkEaEdJK73bbd/9PQYtb2pnzxmVC9e6fCyhSahArOO
      64ZEwCkCgYEA4N9a+rb0CxJwvnazgWi4keVFBEzEkrP0wNoGPrTweU71U/l1PwGq
      JsnHmaPg+6y4CsLUIqjwx44jHb8pLkOZqXzzbHiUJPinahrZvdkU5KDvqeTuS9QS
      pU4/jUf6vJTxRcbYBf1WhcB4BM4vAmv2PQOaUDTNwyLj3LKh8J44FK0CgYEAxRno
      NZSqXLdaNoDLSja6SjIt3WLNzKrfpDXspZNnsgt8JMKuyl7slOT2d2m6rZKAkcHr
      2Ss9Dm29QHu6U6GKdBrpLKwMczfYINlB5ItEza2v+6lF7wn2R+8UWTZVPLU7FbuY
      JE0aRRVg9AdU7VdQVge/7ZBgKDTozqZ+mT6DGO8CgYEApkmkzoeiGdnuE3pVrZmR
      +xlOmyplppJ6qG3Rdmd4+EvCMPHkmM4TVBGcj2nXQmTrx9Fg66yAOSFLqICm5DZL
      GEF1BL551okly9nFMJWp1JOKBtlquho+G42sgz46FWAStuWe83bul4PHfM43hxPt
      CBt07mDN08ImPBrAk918XRUCgYEAkv2WIldjkc+fdKQqd4dG+MxhTghAaJFKReF9
      QaIjpDFSfOu/hOaz0vrKIBX2hTmLrqgLZqMLXrZSfEOJmpMPeTUUjh8lDcwo356G
      uJVwU19jre/4WqN4Sv8ukrWlbafOj4+ej/v8Smb+Lh9Fo9cI74/J/7Y7L+D9ehfK
      tChdhnsCgYBlsXVGLMI/FsriHmO03fNs4Gks1ju5khjgeNijJWgiq4pMIf2r22u5
      nv68qsq9v/9tO7jD16stFkFxQnMUFm7UFOYPdAeJC7t8GIXhH1e5qgAcxRvnR0R+
      BMMedpgUJ0BocK63CB+m6j2jrv5DxXOrKJqoLIiWgRbyYRjjbmvCZg==
      -----END RSA PRIVATE KEY-----

- name: test-repo
  type: git
  icon: github-circle 
  source: 
    uri: "https://github.com/nayamama/concourse_pp_test.git"
    branch: master

- name: my-timer
  type: time
  source:
    interval: 2m

jobs:
  - name: map-resource-in-another-folder
    public: true
    plan:
      - get: git-repo
      - get: test-repo
      - get: my-timer
        trigger: true
      - task: check-folder-structure
        file: test-repo/commit_output/update_repo.yml
      - put: git-repo
        params:
          repository: update-git
