resources:
- name: git-repo
  public: true
  type: git
  icon: github-circle 
  source: 
    #uri: "https://github.com/nayamama/groovy_java.git"  # not working
    uri: "git@github.com:nayamama/groovy_java.git"
    branch: master
    private_key: {{github-private-key}}

- name: test-repo
  type: git
  icon: github-circle 
  source: 
    uri: "https://github.com/nayamama/concourse_pp_test.git"
    branch: master

- name: my-timer
  type: time
  source:
    interval: 2m

jobs:
  - name: upgrade-commit
    plan:
      - get: git-repo
      - get: test-repo
      - get: my-timer
        trigger: true
      - task: upgrade_commit
        file: test-repo/commit_output/update_repo.yml
      - put: git-repo
        params:
          repository: update-git

  - name: fetch-commit
    public: true
    plan:
      - get: git-repo
        trigger: true
        passed: [upgrade-commit]
      - get: test-repo
      - task: show-new-update
        file: test-repo/commit_output/show_new_date.yml
        
